### ISSUE TITLE
Use cases for JsonPathMatch.parent

### ISSUE THREAD

**Issue by f3ath** [peiffer-innovations/template_expressions#26]
Hey @jpeiffer , I'm working on v0.5 of `json_path` and checking the existing usages to make sure I'm not breaking something important. Curious about use cases of [JsonPathMatch.parent](https://github.com/peiffer-innovations/template_expressions/blob/5a25afcb933d422b911f859a531af4733c3f753a/lib/src/expressions/standard_members.dart#L349) property. It's going to be dropped in v0.5, how big of an impact will it make?

**Comment by jpeiffer** [comment]
No particular reason.  I exposed it because it existed, and that's as much thought that I put in it.  I saw you removed it in v0.5, so I just removed it here and bumped the major version to signify a breaking change.

Thanks for the heads up.
