### ISSUE TITLE
Support for NumberFormat

### ISSUE THREAD

**Issue by jsroest** [peiffer-innovations/template_expressions#67]
Hi, I'm working on support for the NumberFormat function.
Are you interested in a PR?

**Comment by jpeiffer** [comment]
Always interested in PRs.

**Comment by jpeiffer** [comment]
I'm going to close this because as of 3.3.0, NumberFormat is now built in.  If you have future issues, concerns, or whatever, please feel free to open a new issue and I will restate... PR's are _**alwats**_ welcome.
